import React, { useState } from 'react';
import { ShieldAlert, BrainCircuit, Activity, Eye, User, UploadCloud, FileJson, FileText, Printer } from 'lucide-react';

export default function App() {
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  const handleFileUpload = async (event) => {
    const file = event.target.files[0];
    if (!file) return;
    setLoading(true); setError(null); setData(null);
    const formData = new FormData(); formData.append("file", file);

    try {
      const response = await fetch("http://localhost:8000/analyze-file", { method: "POST", body: formData });
      const result = await response.json();
      if (!response.ok) throw new Error(result.detail || "Failed to process the payload.");
      setData(result);
    } catch (err) { setError(err.message); } 
    finally { setLoading(false); }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-gray-900 text-white p-8 font-sans print:bg-white print:text-black print:p-0">
      
      {/* HEADER - Hides when printing */}
      <header className="mb-10 text-center print:hidden">
        <h1 className="text-4xl font-bold flex justify-center items-center gap-3 text-red-500 mb-2">
          <ShieldAlert size={40} /> TRACKGRAM Nexus
        </h1>
        <p className="text-gray-400">Tactical Intelligence & Behavioral Profiling</p>
      </header>

      {/* PDF REPORT HEADER - Only shows when printing */}
      <div className="hidden print:block mb-8 border-b-2 border-black pb-4">
        <h1 className="text-3xl font-black uppercase tracking-widest">CONFIDENTIAL OSINT REPORT</h1>
        <p className="text-sm">Generated by TRACKGRAM Nexus | Date: {new Date().toLocaleDateString()}</p>
      </div>

      {!data && !loading && (
        <div className="max-w-2xl mx-auto border-2 border-dashed border-gray-600 rounded-xl p-12 text-center hover:border-red-500 transition-colors bg-gray-800 shadow-xl print:hidden">
          <UploadCloud size={60} className="mx-auto text-gray-400 mb-4" />
          <h3 className="text-2xl font-bold mb-2">Inject Intelligence Payload</h3>
          <p className="text-gray-400 mb-6">Upload .json to run Deep Behavioral Analysis.</p>
          <label className="bg-red-600 hover:bg-red-700 text-white px-8 py-4 rounded-lg cursor-pointer font-bold inline-flex items-center gap-2">
            <FileJson size={20} /> Select File
            <input type="file" accept=".json" onChange={handleFileUpload} className="hidden" />
          </label>
        </div>
      )}

      {loading && (
        <div className="text-center mt-20 animate-pulse print:hidden">
          <BrainCircuit size={60} className="mx-auto text-red-500 mb-4 animate-spin" />
          <h2 className="text-2xl font-bold">Synthesizing Intelligence...</h2>
        </div>
      )}

      {error && (
        <div className="max-w-2xl mx-auto bg-red-900 border border-red-500 text-red-200 p-4 rounded-lg mt-8 text-center print:hidden">
          <strong>Mission Failed:</strong> {error}
        </div>
      )}

      {data && !loading && (
        <div className="max-w-5xl mx-auto space-y-8 animate-in fade-in zoom-in duration-500">
          
          {/* SECTION A: Account Identification */}
          <div className="bg-gray-800 print:bg-white rounded-xl p-6 border border-gray-700 print:border-gray-300 shadow-lg">
             <h3 className="text-2xl font-black mb-4 border-b border-gray-700 print:border-black pb-2 text-red-500 print:text-black uppercase">
               A. Account Identification & Metadata
             </h3>
             <div className="grid grid-cols-2 gap-4 text-gray-300 print:text-black">
                <p><strong className="text-white print:text-black">Username:</strong> @{data.profile.Username} {data.profile.Is_Verified && "✓"}</p>
                <p><strong className="text-white print:text-black">Internal ID:</strong> {data.profile.Account_ID}</p>
                <p><strong className="text-white print:text-black">Full Name:</strong> {data.profile.Full_Name}</p>
                <p><strong className="text-white print:text-black">Public Stats:</strong> {data.profile.Followers.toLocaleString()} Followers | {data.profile.Following.toLocaleString()} Following</p>
                <p className="col-span-2"><strong className="text-white print:text-black">Biography:</strong> "{data.profile.Biography}"</p>
             </div>
          </div>

          {/* SECTION B: Content Analysis */}
          <div className="bg-gray-800 print:bg-white rounded-xl p-6 border border-gray-700 print:border-gray-300 shadow-lg">
             <h3 className="text-2xl font-black mb-4 border-b border-gray-700 print:border-black pb-2 text-blue-400 print:text-black uppercase">
               B. Content Analysis (Posts, Stories, Reels)
             </h3>
             <p className="text-sm italic text-gray-400 print:text-gray-600 mb-4">Key insight: Patterns often reveal intent more than individual posts.</p>
             
             <ul className="space-y-4 text-gray-300 print:text-black">
               <li className="flex flex-col sm:flex-row sm:justify-between border-b border-gray-700 print:border-gray-200 pb-2">
                 <strong className="text-white print:text-black">Types of Posts:</strong> 
                 <span className="font-mono text-blue-300 print:text-black">{data.content_analysis.post_types}</span>
               </li>
               <li className="flex flex-col sm:flex-row sm:justify-between border-b border-gray-700 print:border-gray-200 pb-2">
                 <strong className="text-white print:text-black">Primary AI Theme Detected:</strong> 
                 <span className="font-mono text-blue-300 print:text-black">{data.content_analysis.primary_theme}</span>
               </li>
               <li className="flex flex-col sm:flex-row sm:justify-between border-b border-gray-700 print:border-gray-200 pb-2">
                 <strong className="text-white print:text-black">Language Patterns & Tone:</strong> 
                 <span className="font-mono text-blue-300 print:text-black">{data.content_analysis.language_tone}</span>
               </li>
               <li className="flex flex-col sm:flex-row sm:justify-between border-b border-gray-700 print:border-gray-200 pb-2">
                 <strong className="text-white print:text-black">Deleted/Edited Content Heuristic:</strong> 
                 <span className="font-mono text-yellow-400 print:text-black">{data.content_analysis.deleted_edited_heuristic}</span>
               </li>
               <li className="flex flex-col sm:flex-row sm:justify-between border-b border-gray-700 print:border-gray-200 pb-2">
                 <strong className="text-white print:text-black">Embedded EXIF Metadata:</strong> 
                 <span className="font-mono text-red-400 print:text-black">{data.content_analysis.exif_metadata}</span>
               </li>
             </ul>
          </div>

          {/* SECTION C: Behavioral Analysis */}
          <div className="bg-gray-800 print:bg-white rounded-xl p-6 border border-gray-700 print:border-gray-300 shadow-lg">
             <h3 className="text-2xl font-black mb-4 border-b border-gray-700 print:border-black pb-2 text-orange-400 print:text-black uppercase">
               C. Behavioral Analysis
             </h3>
             <p className="text-sm italic text-gray-400 print:text-gray-600 mb-4">Focus on how the account behaves over time.</p>
             
             <ul className="space-y-4 text-gray-300 print:text-black">
               <li className="flex flex-col sm:flex-row sm:justify-between border-b border-gray-700 print:border-gray-200 pb-2">
                 <strong className="text-white print:text-black">Posting Schedule:</strong> 
                 <span className="font-mono text-orange-300 print:text-black">{data.behavioral_analysis.posting_schedule}</span>
               </li>
               <li className="flex flex-col sm:flex-row sm:justify-between border-b border-gray-700 print:border-gray-200 pb-2">
                 <strong className="text-white print:text-black">Sudden Spikes in Activity:</strong> 
                 <span className="font-mono text-orange-300 print:text-black">{data.behavioral_analysis.sudden_spikes}</span>
               </li>
               <li className="flex flex-col sm:flex-row sm:justify-between border-b border-gray-700 print:border-gray-200 pb-2">
                 <strong className="text-white print:text-black">Automation Indicators:</strong> 
                 <span className="font-mono text-orange-300 print:text-black">{data.behavioral_analysis.automation_indicators}</span>
               </li>
               <li className="flex flex-col sm:flex-row sm:justify-between border-b border-gray-700 print:border-gray-200 pb-2">
                 <strong className="text-white print:text-black">Engagement Tactics:</strong> 
                 <span className="font-mono text-orange-300 print:text-black">{data.behavioral_analysis.engagement_tactics}</span>
               </li>
               <li className="flex flex-col sm:flex-row sm:justify-between border-b border-gray-700 print:border-gray-200 pb-2">
                 <strong className="text-white print:text-black">Story Usage Patterns:</strong> 
                 <span className="font-mono text-orange-300 print:text-black">{data.behavioral_analysis.story_patterns}</span>
               </li>
             </ul>
          </div>
          
          {/* Action Buttons */}
          <div className="flex justify-center gap-6 mt-12 pb-8 print:hidden">
            <button 
              onClick={handlePrint} 
              className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-8 rounded-lg transition-colors flex items-center gap-2 shadow-lg"
            >
              <Printer size={20}/> Download PDF Report
            </button>
            
            <button 
              onClick={() => setData(null)} 
              className="border-2 border-gray-600 hover:border-gray-400 text-gray-300 font-bold py-3 px-8 rounded-lg transition-colors flex items-center gap-2"
            >
              <UploadCloud size={20}/> Analyze New Target
            </button>
          </div>
        </div>
      )}
    </div>
  );
}